### ISSUE TITLE
CPP lexer error

### ISSUE THREAD

**Issue by matkuki** [matkuki/ExCo#12]
Fix this error when opening a C/C++ file:
```
Traceback (most recent call last):
  File "C:\SK_Na_POT_vd\ExCo\forms.py", line 5468, in dropEvent
    self.parent.open_file(self.drag_dropped_file,  self)
  File "C:\SK_Na_POT_vd\ExCo\forms.py", line 2254, in open_file
    open_file_function(file, basic_widget)
  File "C:\SK_Na_POT_vd\ExCo\forms.py", line 2211, in open_file_function
    new_tab = basic_widget.editor_add_document(in_file, "file", bypass_check=False)
  File "C:\SK_Na_POT_vd\ExCo\forms.py", line 5848, in editor_add_document
    new_editor_tab.choose_lexer(file_type)
  File "C:\SK_Na_POT_vd\ExCo\forms.py", line 8034, in choose_lexer
    lexer   = lexers.CPP()
  File "<string>", line 63, in __init__
  File "<string>", line 73, in set_theme
AttributeError: type object 'CPP' has no attribute 'InactiveEscapeSequence'
```

**Comment by matkuki** [comment]
It happens with this code:
[CE227_ECAN_Crosswire_091207.zip](https://github.com/matkuki/ExCo/files/636312/CE227_ECAN_Crosswire_091207.zip)

**Comment by matkuki** [comment]
Commit a9361a6 fixes this.
