### ISSUE TITLE
TextDiffer crash

### ISSUE THREAD

**Issue by matkuki** [matkuki/ExCo#23]
It crashes when diffing sometimes. (ce.File)

**Comment by matkuki** [comment]
Traceback (most recent call last):
  File "D:\ExCo\forms.py", line 5649, in difference_function
    text_2_name
  File "D:\ExCo\forms.py", line 4911, in show_text_difference
    text_name_2
  File "D:\ExCo\helper_forms.py", line 3513, in __init__
    self.compare(text_1, text_2)
  File "D:\ExCo\helper_forms.py", line 3871, in compare
    list_sum[i+2].startswith("? ")):
IndexError: list index out of range
