### ISSUE TITLE
Cannot run from a read-only location

### ISSUE THREAD

**Issue by probonopd** [matkuki/ExCo#41]
Cannot run from a read-only location. Please make it save its settings in `$XDG_CONFIG_HOME`.

```
% python3 /var/run/user/1001/_home_user_Desktop_ExCo-6.15.zip/ExCo-6.15/main.py 
No module named 'cython_lexers'
No module named 'nim_lexers'
Traceback (most recent call last):
  File "/var/run/user/1001/_home_user_Desktop_ExCo-6.15.zip/ExCo-6.15/main.py", line 154, in <module>
    main()
  File "/var/run/user/1001/_home_user_Desktop_ExCo-6.15.zip/ExCo-6.15/main.py", line 145, in main
    file_arguments=file_arguments
  File "/var/run/user/1001/_home_user_Desktop_ExCo-6.15.zip/ExCo-6.15/gui/mainwindow.py", line 129, in __init__
    self.settings   = self.Settings(self)
  File "/var/run/user/1001/_home_user_Desktop_ExCo-6.15.zip/ExCo-6.15/gui/mainwindow.py", line 2657, in __init__
    data.resources_directory
  File "/var/run/user/1001/_home_user_Desktop_ExCo-6.15.zip/ExCo-6.15/settings.py", line 332, in __init__
    self.create_settings_file(self.empty_settings_list)
  File "/var/run/user/1001/_home_user_Desktop_ExCo-6.15.zip/ExCo-6.15/settings.py", line 343, in create_settings_file
    file = open(self.settings_filename_with_path, "w", encoding="utf-8")
OSError: [Errno 30] Read-only file system: '/var/run/user/1001/_home_user_Desktop_ExCo-6.15.zip/ExCo-6.15/exco.ini'
```

**Comment by matkuki** [comment]
Thanks, will do. Have been meaning to change this to save to `$HOME/.exco/`.

**Comment by matkuki** [comment]
Commit 46eff73a51b48d702b915600174ab035b8c14e44 upgrades this.
